apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/murphye/gloo-quickstarts'
    path: gloo-mesh-enterprise-argo-quickstart/mgmt/gloo-mesh
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gloo-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    createNamespace: true