apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-install
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/murphye/gloo-quickstarts'
    path: gloo-edge-federation-argo-quickstart/gloo-edge/gloo-edge-enterprise
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true