apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: istio-operator
  source:
    repoURL: https://github.com/istio/istio.git
    targetRevision: "1.9.2"
    path: manifests/charts/istio-operator

    helm:
      parameters:
        - name: "operatorNamespace"
          value: "istio-operator"
        - name: "istioNamespace"
          value: "istio-system"

  destination:
    namespace: istio-operator
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true

  syncOptions:
    createNamespace: true

---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: demo