apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  project: default
  source:
    chart: enterprise-agent
    helm:
      values: |
        relay:
          serverAddress: 192.168.86.51:9900
          authority: *.acme.com
          cluster: remote-cluster
          
    repoURL: https://storage.googleapis.com/gloo-mesh-enterprise/enterprise-agent
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    createNamespace: true