apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh-enterprise
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  project: default
  source:
    chart: gloo-mesh-enterprise
    helm:
      values: |
        enterprise-networking:
          enterpriseNetworking:
            serviceType: LoadBalancer
          selfSigned: false
        # Expires 2021-04-19T15:37:23-07:00
        licenseKey: eyJleHAiOjE2MTg4NzE4NDMsImlhdCI6MTYxNzY2MjI0MywiayI6Ijd3cG5NdyIsImx0IjoiZW50IiwicHJvZHVjdCI6Imdsb28tbWVzaCJ9.k7qfp-_Uetl8__oVx9oN47SA0bWYyiknvjypDLvHPwo
    repoURL: https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-enterprise
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true